### ISSUE TITLE
Scrape the digital gujarat notification board

### ISSUE THREAD

**Issue by Rjchauhan18** [Rjchauhan18/gtu_notification#11]
**Description**

You have to scrape the [Digital Gujarat ](https://www.digitalgujarat.gov.in/loginapp/CitizenLogin.aspx) . here You will have Latest Update section which you need to scrap and then you have to check is the first notification is not as the last time then you need send the email and save the title of the notification to some file(create a different file with name : DGtitle) .

- I have already written a bit of code [here](https://github.com/Rjchauhan18/gtu_notification/blob/main/Digital_guj_scraper.py) on this but does not compare the titles of  notification feel free to change the code .

**Comment by BraxtonElmer** [comment]
can i get assigned to this?
